version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns: ["*"]

  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    allow:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    groups:
      python-patches:
        patterns: ["*"]
        update-types: ["patch"]

  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    allow:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    groups:
      rust-patches:
        patterns: ["*"]
        update-types: ["patch"]
