"""Versioned, interpretable soft-fusion model for de-esser setup evidence."""

from __future__ import annotations

import numpy as np

MODEL_VERSION = "deesser-soft-fusion-v1"
CORPUS_VERSION = "audioforge-generated-deesser-corpus-v1"

FRAME_FEATURE_NAMES = (
    "absolute_hf_strength",
    "temporal_hf_excess",
    "noise_reliability",
    "unvoiced_evidence",
    "peak_prominence",
    "peak_location",
)

CLIP_FEATURE_NAMES = (
    "frame_probability_p90",
    "frame_probability_top_mean",
    "candidate_support",
    "temporal_contrast",
    "absolute_hf_strength_p90",
    "noise_reliability_p90",
)

# These coefficients are regenerated by python/tools/evaluate_deesser_corpus.py.
# All inputs are bounded to [0, 1], keeping coefficient direction inspectable.
FRAME_INTERCEPT = -14.745480728063148
FRAME_COEFFICIENTS = np.asarray(
    [
        1.4074734365324453,
        5.220098953258285,
        2.427808017651834,
        1.1022350583682425,
        4.160012489488813,
        2.4617269295476714,
    ],
    dtype=float,
)
CLIP_INTERCEPT = -5.98947017317317
CLIP_COEFFICIENTS = np.asarray(
    [
        2.9145233318588595,
        2.038737680696125,
        0.5664410938494544,
        0.8808711007448764,
        3.440954995939097,
        0.8326905545571951,
    ],
    dtype=float,
)

# Tuned for low false activation: a missed mild case is safer than lisping or
# dulling a voice whose microphone is merely bright.
ENABLE_PROBABILITY_THRESHOLD = 0.4935253581578833


def _sigmoid(logit: np.ndarray | float) -> np.ndarray:
    values = np.asarray(logit, dtype=float)
    positive = values >= 0.0
    result = np.empty_like(values, dtype=float)
    result[positive] = 1.0 / (1.0 + np.exp(-values[positive]))
    exp_values = np.exp(values[~positive])
    result[~positive] = exp_values / (1.0 + exp_values)
    return result


def predict_frame_probabilities(feature_rows: np.ndarray) -> np.ndarray:
    """Return calibrated fixture-model probability for each analysis frame."""
    features = np.asarray(feature_rows, dtype=float)
    if features.ndim != 2 or features.shape[1] != len(FRAME_FEATURE_NAMES):
        raise ValueError(
            f"expected frame features with shape (n, {len(FRAME_FEATURE_NAMES)})"
        )
    bounded = np.clip(features, 0.0, 1.0)
    return _sigmoid(FRAME_INTERCEPT + bounded @ FRAME_COEFFICIENTS)


def predict_clip_probability(features: np.ndarray) -> float:
    """Return continuous clip-level probability that de-essing is warranted."""
    values = np.asarray(features, dtype=float).reshape(-1)
    if values.size != len(CLIP_FEATURE_NAMES):
        raise ValueError(f"expected {len(CLIP_FEATURE_NAMES)} clip features")
    bounded = np.clip(values, 0.0, 1.0)
    return float(_sigmoid(CLIP_INTERCEPT + np.dot(bounded, CLIP_COEFFICIENTS)))


__all__ = [
    "CLIP_COEFFICIENTS",
    "CLIP_FEATURE_NAMES",
    "CLIP_INTERCEPT",
    "CORPUS_VERSION",
    "ENABLE_PROBABILITY_THRESHOLD",
    "FRAME_COEFFICIENTS",
    "FRAME_FEATURE_NAMES",
    "FRAME_INTERCEPT",
    "MODEL_VERSION",
    "predict_clip_probability",
    "predict_frame_probabilities",
]
