"""Shared constants for Auto-EQ analysis."""
import os

from mic_eq.config import AUTO_EQ_DEFAULT_Q

DEBUG = os.environ.get("AUDIOFORGE_DEBUG", "").strip().lower() in {"1", "true", "yes", "on"}
SAMPLE_RATE = 48_000.0
NUM_EQ_BANDS = 10
GAIN_MIN_DB = -12.0
GAIN_MAX_DB = 12.0
Q_PRIOR = AUTO_EQ_DEFAULT_Q
Q_MIN = 0.3
Q_MAX = 6.0
LOW_BAND_Q_MAX = 2.5
LOW_BAND_Q_MAX_HZ = 250.0
DENSE_GRID_POINTS = 256
VOICE_WEIGHT = 2.0
OUT_OF_BAND_WEIGHT = 0.8
LAMBDA_Q = 10.0
LAMBDA_G = 0.35
LAMBDA_CENTER = 16.0
LAMBDA_TILT = 0.08
LAMBDA_COUPLING = 8.0
MAX_ADJ_GAIN_DIFF_DB = 6.0
TILT_FIT_MIN_HZ = 100.0
TILT_FIT_MAX_HZ = 8000.0
TILT_MIN_FIT_R2 = 0.65
SNR_MIN_DB = 3.0
SNR_FULL_DB = 18.0
SNR_LOW_RELIABILITY_WEIGHT = 0.35
SNR_LOW_RELIABILITY_MAX_BOOST_DB = 3.0
DYNAMIC_LOW_SHELF_RANGE_HZ = (55.0, 180.0)
DYNAMIC_PEAK_RANGE_HZ = (200.0, 9000.0)
DYNAMIC_HIGH_SHELF_RANGE_HZ = (9500.0, 18_000.0)
DYNAMIC_CENTER_REFINE_PCT = 0.25
DYNAMIC_SHELF_CENTER_REFINE_PCT = 0.18
DYNAMIC_PEAK_MIN_SEPARATION_OCT = 0.34
DYNAMIC_MEANINGFUL_CORRECTION_DB = 0.75


def debug_log(message: str) -> None:
    if DEBUG:
        print(message)
