"""Internal configuration implementation helpers."""

from .app_config import AppConfig, load_config, save_config
from .presets import Preset, generate_auto_eq_preset_name, list_presets, load_preset, save_preset
from .settings import (
    ANALYSIS_MAX_SPECTRAL_FLATNESS,
    ANALYSIS_MIN_DYNAMIC_RANGE,
    ANALYSIS_MIN_PEAK_COUNT,
    ANALYSIS_MIN_SNR,
    AUTO_EQ_DEFAULT_Q,
    CompressorSettings,
    DeEsserSettings,
    EQSettings,
    EQ_FREQUENCIES,
    GateSettings,
    LatencyCalibrationProfile,
    LimiterSettings,
    RNNoiseSettings,
    TargetCurve,
)
from .shared import (
    APPDATA_DIR_NAME,
    CURRENT_VERSION,
    DeviceIdentity,
    LEGACY_APPDATA_DIR_NAME,
    PresetValidationError,
    build_latency_profile_key,
    coerce_device_identity,
    get_config_file,
    get_preset_imports_dir,
    get_presets_dir,
    legacy_latency_profile_key,
    parse_latency_profile_key,
)
from .validation import VALIDATION_RANGES

__all__ = [
    "ANALYSIS_MAX_SPECTRAL_FLATNESS",
    "ANALYSIS_MIN_DYNAMIC_RANGE",
    "ANALYSIS_MIN_PEAK_COUNT",
    "ANALYSIS_MIN_SNR",
    "APPDATA_DIR_NAME",
    "AUTO_EQ_DEFAULT_Q",
    "AppConfig",
    "CURRENT_VERSION",
    "CompressorSettings",
    "DeEsserSettings",
    "DeviceIdentity",
    "EQSettings",
    "EQ_FREQUENCIES",
    "GateSettings",
    "LatencyCalibrationProfile",
    "LEGACY_APPDATA_DIR_NAME",
    "LimiterSettings",
    "Preset",
    "PresetValidationError",
    "RNNoiseSettings",
    "TargetCurve",
    "VALIDATION_RANGES",
    "build_latency_profile_key",
    "coerce_device_identity",
    "generate_auto_eq_preset_name",
    "get_config_file",
    "get_preset_imports_dir",
    "get_presets_dir",
    "legacy_latency_profile_key",
    "list_presets",
    "load_config",
    "load_preset",
    "parse_latency_profile_key",
    "save_config",
    "save_preset",
]
