"""Typing surface for the PyO3 extension implemented in ``rust-core``."""

from collections.abc import Mapping, Sequence
from typing import Any

import numpy as np
import numpy.typing as npt


class DeviceInfo:
    name: str
    is_default: bool

    def __repr__(self) -> str: ...


class AudioProcessor:
    def __init__(self) -> None: ...
    def start(
        self, input_device: str | None = None, output_device: str | None = None
    ) -> str: ...
    def stop(self) -> None: ...
    def is_running(self) -> bool: ...
    def get_active_input_device(self) -> str | None: ...
    def get_active_output_device(self) -> str | None: ...
    def sample_rate(self) -> int: ...
    def set_bypass(self, bypass: bool) -> None: ...
    def is_bypass(self) -> bool: ...
    def set_raw_monitor_enabled(self, enabled: bool) -> None: ...
    def is_raw_monitor_enabled(self) -> bool: ...
    def set_input_channel_mode(self, mode: str) -> None: ...
    def get_input_channel_mode(self) -> str: ...
    def set_input_cleanup_mode(self, mode: str) -> None: ...
    def get_input_cleanup_mode(self) -> str: ...
    def set_gate_enabled(self, enabled: bool) -> None: ...
    def is_gate_enabled(self) -> bool: ...
    def get_gate_chatter_event_count(self) -> int: ...
    def set_gate_threshold(self, threshold_db: float) -> None: ...
    def set_gate_attack(self, attack_ms: float) -> None: ...
    def set_gate_release(self, release_ms: float) -> None: ...
    def set_gate_mode(self, mode: int) -> None: ...
    def get_vad_probability(self) -> float: ...
    def get_gate_fused_score(self) -> float: ...
    def is_vad_available(self) -> bool: ...
    def set_vad_threshold(self, threshold: float) -> None: ...
    def set_vad_hold_time(self, hold_ms: float) -> None: ...
    def set_vad_pre_gain(self, gain: float) -> None: ...
    def set_auto_threshold(self, enabled: bool) -> None: ...
    def set_gate_margin(self, margin_db: float) -> None: ...
    def get_noise_floor(self) -> float: ...
    def gate_margin(self) -> float: ...
    def auto_threshold_enabled(self) -> bool: ...
    def vad_pre_gain(self) -> float: ...
    def set_rnnoise_enabled(self, enabled: bool) -> None: ...
    def is_rnnoise_enabled(self) -> bool: ...
    def set_rnnoise_strength(self, strength: float) -> None: ...
    def get_rnnoise_strength(self) -> float: ...
    def set_noise_model(self, model: str) -> bool: ...
    def get_noise_model(self) -> str: ...
    def get_noise_model_display_name(self) -> str: ...
    def list_noise_models(self) -> list[tuple[str, str]]: ...
    def set_eq_enabled(self, enabled: bool) -> None: ...
    def is_eq_enabled(self) -> bool: ...
    def set_eq_band_gain(self, band: int, gain_db: float) -> None: ...
    def set_eq_band_frequency(self, band: int, frequency: float) -> None: ...
    def set_eq_band_q(self, band: int, q: float) -> None: ...
    def get_eq_band_params(self, band: int) -> tuple[float, float, float] | None: ...
    def apply_eq_settings(self, bands: Sequence[tuple[float, float, float]]) -> None: ...
    def set_deesser_enabled(self, enabled: bool) -> None: ...
    def is_deesser_enabled(self) -> bool: ...
    def set_deesser_low_cut_hz(self, hz: float) -> None: ...
    def set_deesser_high_cut_hz(self, hz: float) -> None: ...
    def set_deesser_threshold_db(self, threshold_db: float) -> None: ...
    def set_deesser_ratio(self, ratio: float) -> None: ...
    def set_deesser_attack_ms(self, attack_ms: float) -> None: ...
    def set_deesser_release_ms(self, release_ms: float) -> None: ...
    def set_deesser_max_reduction_db(self, max_reduction_db: float) -> None: ...
    def set_deesser_auto_enabled(self, auto_enabled: bool) -> None: ...
    def is_deesser_auto_enabled(self) -> bool: ...
    def set_deesser_auto_amount(self, amount: float) -> None: ...
    def get_deesser_low_cut_hz(self) -> float: ...
    def get_deesser_high_cut_hz(self) -> float: ...
    def get_deesser_threshold_db(self) -> float: ...
    def get_deesser_ratio(self) -> float: ...
    def get_deesser_max_reduction_db(self) -> float: ...
    def get_deesser_auto_amount(self) -> float: ...
    def get_deesser_gain_reduction_db(self) -> float: ...
    def get_deesser_detector_confidence(self) -> float: ...
    def set_compressor_enabled(self, enabled: bool) -> None: ...
    def is_compressor_enabled(self) -> bool: ...
    def set_compressor_threshold(self, threshold_db: float) -> None: ...
    def set_compressor_ratio(self, ratio: float) -> None: ...
    def set_compressor_attack(self, attack_ms: float) -> None: ...
    def set_compressor_release(self, release_ms: float) -> None: ...
    def get_compressor_release(self) -> float: ...
    def set_compressor_makeup_gain(self, makeup_gain_db: float) -> None: ...
    def set_compressor_adaptive_release(self, enabled: bool) -> None: ...
    def get_compressor_adaptive_release(self) -> bool: ...
    def set_compressor_base_release(self, release_ms: float) -> None: ...
    def get_compressor_base_release(self) -> float: ...
    def set_compressor_sidechain_highpass_enabled(self, enabled: bool) -> None: ...
    def get_compressor_sidechain_highpass_enabled(self) -> bool: ...
    def get_compressor_current_release(self) -> float: ...
    def set_compressor_auto_makeup_enabled(self, enabled: bool) -> None: ...
    def get_compressor_auto_makeup_enabled(self) -> bool: ...
    def set_compressor_target_lufs(self, target_lufs: float) -> None: ...
    def get_compressor_target_lufs(self) -> float: ...
    def get_compressor_current_lufs(self) -> float: ...
    def get_compressor_current_makeup_gain(self) -> float: ...
    def set_limiter_enabled(self, enabled: bool) -> None: ...
    def is_limiter_enabled(self) -> bool: ...
    def set_limiter_ceiling(self, ceiling_db: float) -> None: ...
    def set_limiter_release(self, release_ms: float) -> None: ...
    def set_limiter_careful_output_enabled(self, enabled: bool) -> None: ...
    def is_limiter_careful_output_enabled(self) -> bool: ...
    def get_limiter_effective_ceiling_db(self) -> float: ...
    def get_input_peak_db(self) -> float: ...
    def get_input_rms_db(self) -> float: ...
    def get_input_crest_factor_db(self) -> float: ...
    def get_output_peak_db(self) -> float: ...
    def get_output_rms_db(self) -> float: ...
    def get_output_crest_factor_db(self) -> float: ...
    def get_output_short_term_lufs(self) -> float: ...
    def get_input_stereo_correlation(self) -> float: ...
    def get_input_phase_warning_count(self) -> int: ...
    def get_compressor_gain_reduction_db(self) -> float: ...
    def get_latency_ms(self) -> float: ...
    def set_latency_compensation_ms(self, compensation_ms: float) -> None: ...
    def get_latency_compensation_ms(self) -> float: ...
    def get_dsp_time_ms(self) -> float: ...
    def get_input_buffer_samples(self) -> int: ...
    def get_input_buffer_smoothed_samples(self) -> int: ...
    def get_output_buffer_samples(self) -> int: ...
    def output_sample_rate(self) -> int: ...
    def get_rnnoise_buffer_samples(self) -> int: ...
    def get_dsp_time_smoothed_ms(self) -> float: ...
    def get_buffer_smoothed_samples(self) -> int: ...
    def get_dropped_samples(self) -> int: ...
    def reset_dropped_samples(self) -> None: ...
    def get_lock_contention_count(self) -> int: ...
    def reset_lock_contention_count(self) -> None: ...
    def get_input_callback_age_ms(self) -> int: ...
    def get_output_callback_age_ms(self) -> int: ...
    def get_output_underrun_streak(self) -> int: ...
    def get_output_underrun_total(self) -> int: ...
    def get_jitter_dropped_samples(self) -> int: ...
    def get_output_retime_adjustment_count(self) -> int: ...
    def get_output_recovery_event_count(self) -> int: ...
    def get_output_recovery_count(self) -> int: ...
    def get_suppressor_non_finite_count(self) -> int: ...
    def get_rt_error_code(self) -> int: ...
    def get_rt_error_name(self) -> str: ...
    def get_input_callback_error_count(self) -> int: ...
    def get_output_callback_error_count(self) -> int: ...
    def get_rt_buffer_overflow_count(self) -> int: ...
    def is_noise_backend_available(self) -> bool: ...
    def noise_backend_failed(self) -> bool: ...
    def noise_backend_error(self) -> str | None: ...
    def set_recovery_suppressed(self, suppressed: bool) -> None: ...
    def is_recovery_suppressed(self) -> bool: ...
    def get_runtime_diagnostics(self) -> dict[str, Any]: ...
    def service_recovery(self) -> bool | None: ...
    def is_recovery_requested(self) -> bool: ...
    def is_recovering(self) -> bool: ...
    def get_stream_restart_count(self) -> int: ...
    def get_last_stream_error(self) -> str | None: ...
    def get_last_restart_reason(self) -> str | None: ...
    def start_raw_recording(self, duration_secs: float) -> None: ...
    def stop_raw_recording(self) -> npt.NDArray[np.float32]: ...
    def is_recording_complete(self) -> bool: ...
    def recording_progress(self) -> float: ...
    def recording_level_db(self) -> float: ...
    def set_output_mute(self, muted: bool) -> None: ...


def list_input_devices() -> list[DeviceInfo]: ...
def list_output_devices() -> list[DeviceInfo]: ...
def simulate_auto_eq_chain(
    audio: npt.NDArray[np.float32],
    sample_rate: float,
    bands: Sequence[tuple[float, float, float]],
    settings: Mapping[str, object] | None = None,
) -> dict[str, Any]: ...
def configure_deepfilter_runtime_paths(
    library_path: str | None = None, model_path: str | None = None
) -> None: ...
